# ----
# Site

title: Justice Template
description: Jekyll template with example content for a law firm.
url:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname: justice-jekyll-template.disqus.com

author:
  name:
  email:
  twitter: # twitter username without the @ symbol


# -----
# Build

collections:
  - staff

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /uploads/building.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

permalink: pretty

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

call_to_actions:
  - Contact
  - Advice
  - Map

