# ----
# Site

title: Justice Template
url: http://orchid-heron.cloudvent.net
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname: justice-jekyll-template.disqus.com

# Default description in social shares for the jekyll-seo-tag gem
description: Jekyll template with example content for a law firm.

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
social:
  name: Ben Balter
  links:
    - https://twitter.com/BenBalter
    - https://www.facebook.com/ben.balter
    - https://www.linkedin.com/in/BenBalter
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter

# -----
# Build

paginate: 1
paginate_path: "/advice/page-:num/"

collections:
  - "staff_members"

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: /uploads/building.jpg
      image: /uploads/building.jpg
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post

permalink: pretty

jekyll-archives:
  enabled:
    - categories

gems:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

call_to_actions:
  - Contact
  - Advice
  - Map

